# 关键问题

1. 除了 resolve 和 reject 能改变 promise 的状态还能如何改变？

```javascript
new Promise((resolve, reject) => {
      throw new Error('fail'); // 抛出异常，promise 变为 rejected 状态，reason 为抛出的 error
    }).then(
      v => {
        console.log(v);
      }
    ).catch(
      err => {
        console.log(err);
      }
    )
```

答：抛出异常：如果当前是 pending 就会变为 rejected。
2. 如果一个 promise 指定了多个成功/失败的回调，都会被调用吗？

```javascript
const p = new Promise((resolve, reject) => {
      resolve(1);
    })
p.then(val => {
      console.log('我是指定的第一个回调函数');
    })
p.then(val => {
      console.log('我是指定的第二个回调函数');
    })
/* 我是指定的第一个回调函数
   我是指定的第二个回调函数
*/
```

答：全部调用。
3. 改变 promise 状态和指定回调函数谁先谁后？
都有可能，正常情况下是先指定回调再改变状态，但也可先改变状态再指定回调：
如何先改变状态后指定回调？
（1）在执行器中直接调用resolve（）/reject（）
    new Promise((resolve,reject) => {
        resolve(1)
    }).then(
        value => {},
        reason => {}
    )

（2）延迟更长时间才调用then（）
    const p = new Promise((resolve,reject) => {
        setTimeout(()=> {
            resolve(1)
        },1000)
    })
    setTimeout(() => {
        p.then(
            value => {},
            reason => {}
        )
    },1500)
4. 链式调用 promise.then() 返回的新 promise 结果状态由什么决定？（看html案例）
(1)简单表达：由then() 指定的回调函数执行的结果决定
(2)详细表达：若抛出异常，新 promise 变为 rejected 状态，reason 为抛出的异常
            若返回的是非promise的任意值，新 promise 变为 resolved，value 为返回值
            若返回的是另一个新 promise，此 promise 的结果就会成为新 promise 的结果
5. promise如何串联多个操作任务？
(1)promise的.then()返回一个新的promise，可以开成then()的链式调用
(2)通过then的链式调用串联多个同步/异步任务
6. 在一组链式调用中，只需要写一个 catch
只要前面有任何一个异步操作执行 rejected 了，都会跳过所有 .then 进入最后的 catch 中
7. 执行器中的 resolve/reject 后面的代码会执行吗？
会正常执行，如果加上 return 就不会执行了

```javascript
p1 = new Promise((resolve, reject) => {
        resolve('resolev in p1');
        console.log('content after p1 resolve'); // 会执行
      })

p2 = new Promise((resolve, reject) => {
        return resolve('resolev in p2');
        console.log('content after p2 return') // 不会执行
      })
```
